spring:
  profiles:
    active: dev
  application:
    name: Homenvi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iems_monitor?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false
    username: iems
    password: iems
    name: homenvi-db
  redis:
    host: localhost
    database: 0
  influx:
    user: admin
    password: wcc
    url: http://localhost:8086/
  mail:
    host: smtp.163.com
    username: imchengwang@163.com
    password: TTcheng0314

homenvi:
  secret-key: c54a32d70ea36c118a651aec11fe747f
  influx-measurement: collections
  influx-database: homenvi

mybatis:
  mapper-locations:
    - classpath*:/mapper/*Mapper.xml
    - classpath*:/mapper/*/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: error
#    me.wcc.base: debug
#    me.wcc.auth: debug
#    me.wcc.homenvi: debug
  #    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread][%level] %logger- %msg%n"
server:
  port: 8880
#security:
#  oauth2:
#    authorization:

# swagger
swagger:
  enabled: true
  title: Homenvi
  description: Homenvi API
  contact:
    name: WangChuncheng
    url: github.com/ttcheng
    email: ttchengwang@foxmail.com
  base-package: me.wcc.
  ui-config:
    display-request-duration: true
    submit-methods: get,post,put,delete
    request-timeout: 5000
    json-editor: true
    show-request-headers: true