spring:
  application:
    name: Homenvi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.181.189:3306/iems_monitor?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: iems
    password: iems
    name: iems
  redis:
    host: localhost
    database: 0
#  main:
#    allow-bean-definition-overriding: true

mybatis:
  mapper-locations:
    - classpath*:/mapper/*Mapper.xml
    - classpath*:/mapper/*/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    me.wcc.base: debug
    me.wcc.auth: debug
    me.wcc.iems: debug
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread][%level] %logger- %msg%n"
server:
  port: 8880
#security:
#  oauth2:
#    authorization:

# swagger
swagger:
  enabled: true
  title: Homenvi
  description: Homenvi API
  contact:
    name: WangChuncheng
    url: github.com/ttcheng
    email: ttchengwang@foxmail.com
  base-package: me.wcc.
  ui-config:
    display-request-duration: true
    submit-methods: get,post,put,delete
    request-timeout: 5000
    json-editor: true
    show-request-headers: true